set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_ENV_PASSTHROUGH PATH)

set(VCPKG_CMAKE_SYSTEM_NAME MinGW)

set(VCPKG_BUILD_TYPE release)
set(VCPKG_C_FLAGS "-D_WIN32_WINNT=0x0A00 -DOPENSSL_NO_ASM")
set(VCPKG_CXX_FLAGS "-D_WIN32_WINNT=0x0A00 -DOPENSSL_NO_ASM")
set(VCPKG_SET_CHARSET_FLAG ON)
list(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_ASM_NASM_COMPILER=nasm")
